// Code generated by "stringer -type fieldType"; DO NOT EDIT

package sip2

import "fmt"

const _fieldType_name = "FieldUnknownFieldAlertFieldAvialableFieldCardRetainedFieldChargedItemsCountFieldFineItemsCountFieldHoldItemsCountFieldOverdueItemsCountFieldRecallItemsCountFieldUnavailableHoldsCountFieldCheckinOKFieldCheckoutOKFieldCirulationStatusFieldDateTimeSyncFieldDesentisizeFieldEndSessionFieldHoldModeFieldItemPropertiesOKFieldLanguageFieldMagneticMediaFieldMaxPrintWidthFieldNbDueDateFieldNoBlockFieldOffLineOKFieldOKFieldOnLineStatusFieldPatronStatusFieldPaymentAcceptedFieldPaymentTypeFieldProtocolVersionFieldPWDAlgorithmFieldRenewalOKFieldRenewedCountFieldResentisizeFieldRetriesAllowdFieldReturnDateFieldRenewalPolicyFieldSecurityMarkerFieldStatusCodeFieldStatusUpdateOKFieldSummaryFieldThirdPartyAllowdFieldTimeoutPeriodFieldTransactionDateFieldUIDAlgorithmFieldUnrenewedCountFieldPatronIdentifierFieldItemIdentifierFieldTerminalPasswordFieldPatronPasswordFieldPersonalNameFieldScreenMessageFieldPrintLineFieldDueDateFieldTitleIdentifierFieldBlockedCardMsgFieldLibraryNameFieldTerminalLocationFieldInstitutionIDFieldCurrentLocationFieldPermanentLocationFieldHoldItemsFieldOverdueItemsFieldChargedItemsFieldFineItemsFieldHomeAddressFieldEmailAddressFieldHomePhoneNumberFieldOwnerFieldCurrenyTypeFieldCancelFieldTransactionIDFieldValidPatronFieldRenewedItemsFieldUnrenewedItemsFieldFeeAcknowledgedFieldStartItemFieldEndItemFieldQueuePositionFieldPickupLocationFieldFeeTypeFieldRecallItemsFieldFeeAmountFieldExpirationDateFieldSupportedMessagesFieldHoldTypeFieldHoldItemsLimitFieldOverdueItemsLimitFieldChargedItemsLimitFieldFeeLimitFieldUnavailableHoldsItemsFieldHoldQueueLengthFieldFeeIdentifierFieldItemPropertiesFieldSecurityInhibitFieldRecallDateFieldMediaTypeFieldSortBinFieldHoldPickupDateFieldLoginUserIDFieldLoginPasswordFieldLocationCodeFieldValidPatronPasswordFieldSequenceNumberFieldChecksum"

var _fieldType_index = [...]uint16{0, 12, 22, 36, 53, 75, 94, 113, 135, 156, 182, 196, 211, 232, 249, 265, 280, 293, 314, 327, 345, 363, 377, 389, 403, 410, 427, 444, 464, 480, 500, 517, 531, 548, 564, 582, 597, 615, 634, 649, 668, 680, 701, 719, 739, 756, 775, 796, 815, 836, 855, 872, 890, 904, 916, 936, 955, 971, 992, 1010, 1030, 1052, 1066, 1083, 1100, 1114, 1130, 1147, 1167, 1177, 1193, 1204, 1222, 1238, 1255, 1274, 1294, 1308, 1320, 1338, 1357, 1369, 1385, 1399, 1418, 1440, 1453, 1472, 1494, 1516, 1529, 1555, 1575, 1593, 1612, 1632, 1647, 1661, 1673, 1692, 1708, 1726, 1743, 1767, 1786, 1799}

func (i fieldType) String() string {
	if i < 0 || i >= fieldType(len(_fieldType_index)-1) {
		return fmt.Sprintf("fieldType(%d)", i)
	}
	return _fieldType_name[_fieldType_index[i]:_fieldType_index[i+1]]
}
